version: "3"
services: 
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports: 
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/postgresql/data
